CREATE TYPE "public"."booking_status" AS ENUM('pending', 'approved', 'rejected', 'cancelled');--> statement-breakpoint
CREATE TYPE "public"."driver_status" AS ENUM('active', 'on_leave', 'inactive');--> statement-breakpoint
CREATE TYPE "public"."trip_status" AS ENUM('pending', 'scheduled', 'in_progress', 'completed', 'cancelled');--> statement-breakpoint
CREATE TYPE "public"."user_role" AS ENUM('user', 'admin');--> statement-breakpoint
CREATE TYPE "public"."van_status" AS ENUM('active', 'maintenance', 'inactive');--> statement-breakpoint
CREATE TABLE "cross_ride_admin_log" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "cross_ride_admin_log_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"adminId" varchar(255) NOT NULL,
	"action" varchar(255) NOT NULL,
	"entityType" varchar(50) NOT NULL,
	"entityId" varchar(255) NOT NULL,
	"changes" text,
	"description" text,
	"createdAt" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "cross_ride_booking" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "cross_ride_booking_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"userId" varchar(255) NOT NULL,
	"tripId" integer NOT NULL,
	"seatsBooked" integer NOT NULL,
	"status" "booking_status" DEFAULT 'pending' NOT NULL,
	"createdAt" timestamp with time zone DEFAULT now() NOT NULL,
	"updatedAt" timestamp with time zone DEFAULT now()
);
--> statement-breakpoint
CREATE TABLE "cross_ride_driver" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "cross_ride_driver_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"name" varchar(255) NOT NULL,
	"email" varchar(255) NOT NULL,
	"phoneNumber" varchar(20) NOT NULL,
	"licenseNumber" varchar(50) NOT NULL,
	"status" "driver_status" DEFAULT 'active' NOT NULL,
	"createdAt" timestamp with time zone DEFAULT now() NOT NULL,
	"updatedAt" timestamp with time zone DEFAULT now(),
	CONSTRAINT "cross_ride_driver_email_unique" UNIQUE("email"),
	CONSTRAINT "cross_ride_driver_licenseNumber_unique" UNIQUE("licenseNumber")
);
--> statement-breakpoint
CREATE TABLE "cross_ride_trip" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "cross_ride_trip_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"vanId" integer NOT NULL,
	"driverId" integer NOT NULL,
	"route" varchar(255) NOT NULL,
	"departureTime" timestamp with time zone NOT NULL,
	"arrivalTime" timestamp with time zone NOT NULL,
	"seatsAvailable" integer NOT NULL,
	"seatsReserved" integer DEFAULT 0 NOT NULL,
	"status" "trip_status" DEFAULT 'scheduled' NOT NULL,
	"createdAt" timestamp with time zone DEFAULT now() NOT NULL,
	"updatedAt" timestamp with time zone DEFAULT now()
);
--> statement-breakpoint
CREATE TABLE "cross_ride_user" (
	"id" varchar(255) PRIMARY KEY NOT NULL,
	"email" varchar(255) NOT NULL,
	"password" varchar(255) NOT NULL,
	"firstName" varchar(255),
	"lastName" varchar(255),
	"phoneNumber" varchar(20),
	"role" "user_role" DEFAULT 'user' NOT NULL,
	"createdAt" timestamp with time zone DEFAULT now() NOT NULL,
	"updatedAt" timestamp with time zone DEFAULT now(),
	CONSTRAINT "cross_ride_user_email_unique" UNIQUE("email")
);
--> statement-breakpoint
CREATE TABLE "cross_ride_van" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "cross_ride_van_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"name" varchar(255) NOT NULL,
	"plateNumber" varchar(20) NOT NULL,
	"capacity" integer NOT NULL,
	"status" "van_status" DEFAULT 'active' NOT NULL,
	"createdAt" timestamp with time zone DEFAULT now() NOT NULL,
	"updatedAt" timestamp with time zone DEFAULT now(),
	CONSTRAINT "cross_ride_van_plateNumber_unique" UNIQUE("plateNumber")
);
--> statement-breakpoint
ALTER TABLE "cross_ride_admin_log" ADD CONSTRAINT "cross_ride_admin_log_adminId_cross_ride_user_id_fk" FOREIGN KEY ("adminId") REFERENCES "public"."cross_ride_user"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "cross_ride_booking" ADD CONSTRAINT "cross_ride_booking_userId_cross_ride_user_id_fk" FOREIGN KEY ("userId") REFERENCES "public"."cross_ride_user"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "cross_ride_booking" ADD CONSTRAINT "cross_ride_booking_tripId_cross_ride_trip_id_fk" FOREIGN KEY ("tripId") REFERENCES "public"."cross_ride_trip"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "cross_ride_trip" ADD CONSTRAINT "cross_ride_trip_vanId_cross_ride_van_id_fk" FOREIGN KEY ("vanId") REFERENCES "public"."cross_ride_van"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "cross_ride_trip" ADD CONSTRAINT "cross_ride_trip_driverId_cross_ride_driver_id_fk" FOREIGN KEY ("driverId") REFERENCES "public"."cross_ride_driver"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "log_admin_idx" ON "cross_ride_admin_log" USING btree ("adminId");--> statement-breakpoint
CREATE INDEX "log_entity_idx" ON "cross_ride_admin_log" USING btree ("entityType");--> statement-breakpoint
CREATE INDEX "log_date_idx" ON "cross_ride_admin_log" USING btree ("createdAt");--> statement-breakpoint
CREATE INDEX "booking_user_idx" ON "cross_ride_booking" USING btree ("userId");--> statement-breakpoint
CREATE INDEX "booking_trip_idx" ON "cross_ride_booking" USING btree ("tripId");--> statement-breakpoint
CREATE INDEX "booking_status_idx" ON "cross_ride_booking" USING btree ("status");--> statement-breakpoint
CREATE INDEX "driver_email_idx" ON "cross_ride_driver" USING btree ("email");--> statement-breakpoint
CREATE INDEX "driver_status_idx" ON "cross_ride_driver" USING btree ("status");--> statement-breakpoint
CREATE INDEX "trip_van_idx" ON "cross_ride_trip" USING btree ("vanId");--> statement-breakpoint
CREATE INDEX "trip_driver_idx" ON "cross_ride_trip" USING btree ("driverId");--> statement-breakpoint
CREATE INDEX "trip_status_idx" ON "cross_ride_trip" USING btree ("status");--> statement-breakpoint
CREATE INDEX "trip_departure_idx" ON "cross_ride_trip" USING btree ("departureTime");--> statement-breakpoint
CREATE INDEX "email_idx" ON "cross_ride_user" USING btree ("email");--> statement-breakpoint
CREATE INDEX "role_idx" ON "cross_ride_user" USING btree ("role");--> statement-breakpoint
CREATE INDEX "van_plate_idx" ON "cross_ride_van" USING btree ("plateNumber");--> statement-breakpoint
CREATE INDEX "van_status_idx" ON "cross_ride_van" USING btree ("status");